---
#ansible-playbook -i "413fdce82295," saucelabs-playbook.yml -vvv
# - hosts: 413fdce82295
  # connection: docker
- hosts: saucelabs-group
  become: true  
  vars:
    saucelabs_version: 4.4.12
    # Baixar
    # https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz
    saucelabs_download_url: https://saucelabs.com/downloads/sc-{{saucelabs_version}}-linux.tar.gz
    saucelabs_download_dest: /tmp/sc-{{saucelabs_version}}-linux.tar.gz
    saucelabs_dir: /opt/cast/saucelabs
    # saucelabs_dir: /opt/saucelabs
    # saucelabs_dir: /var/lib/jenkins/saucelabs
    sudo: false
    service_name: saucelabs
    saucelabs_user: danilo.ischiavolini
    saucelabs_key: ef3395f5-e975-4e1e-ac05-7abb0585ebb1
    env:
      http_proxy: proxyapp.santanderbr.corp:80
      https_proxy: proxyapp.santanderbr.corp:80
      

  tasks:
  # - name: upgrade all packages
  #   yum:
  #     name: '*'
  #     state: latest

  - name: install wget
    yum:
      name: wget

  - name: create "saucelabs" group
    group: name=saucelabs

  - name: create "saucelabs" user
    user: name=saucelabs group=saucelabs

  - name: create {{saucelabs_dir}} directory
    file: path={{saucelabs_dir}} state=directory
    #when: saucelabs_download.changed    
    
    
  - name: Copia Saucelabs Baixado
    copy: 
      src: "sc-{{saucelabs_version}}-linux.tar.gz"
      dest: "{{saucelabs_download_dest}}"
      owner: saucelabs
      group: saucelabs       

  # - name: download saucelabs
  #   get_url: 
  #     url: "{{saucelabs_download_url}}"
  #     dest: "{{saucelabs_download_dest}}"
  #     validate_certs: false
  #     mode: 0440
  
  - name: extract saucelabs to {{saucelabs_dir}}
    command: tar xzf {{saucelabs_download_dest}} -C {{saucelabs_dir}} --strip-components=1
    #when: saucelabs_download.changed    

  - name: Adicionando liberacao de execucao Saucelabs
    command: chmod +x "{{saucelabs_dir}}/bin/sc"    

  - name: Add Soucelabs symlinks for service management.
    # become: true
    file:
      src: "{{saucelabs_dir}}/bin/sc"
      dest: "{{ item }}"
      state: link
      group: saucelabs 
      owner: saucelabs
    with_items:
      - /usr/bin/sc
      - /etc/init.d/sc
      # - /usr/local/bin/   

  - name: Config Saucelabs user e pass
    copy: 
      src: ./config/sc
      dest: /etc/default/sc
      owner: saucelabs
      group: saucelabs   

  - name: Copy files config systemd
    file: 
      src: "{{saucelabs_dir}}/config_examples/systemd/sc.service"
      dest: /etc/systemd/system/sc.service
      state: link      
      owner: saucelabs
      group: saucelabs    
      
  - name: Copy files config systemd user
    file: 
      src: "{{saucelabs_dir}}/config_examples/systemd/sc@.service"
      dest: /etc/systemd/system/sc@.service
      state: link  
      owner: saucelabs
      group: saucelabs          

  - name: set USER DATA
    lineinfile: dest=/etc/systemd/system/sc@.service regexp="Environment=SAUCE_USERNAME" line="Environment=SAUCE_USERNAME={{saucelabs_user}}" backrefs=true   

  
  - name: set USER DATA
    lineinfile: dest=/etc/systemd/system/sc@.service regexp="Environment=SAUCE_ACCESS_KEY" line="Environment=SAUCE_ACCESS_KEY={{saucelabs_key}}" backrefs=true   
    
  - name: create /etc/systemd/system/sc.service.wants directory
    file: path=/etc/systemd/system/sc.service.wants state=directory


  - name: Add service 8000 e 8001
    # become: true
    file:
      src: /etc/systemd/system/sc@.service
      dest: "{{ item }}"
      state: link
      group: saucelabs 
      owner: saucelabs
    with_items:
      - /etc/systemd/system/sc.service.wants/sc@8000.service
      - /etc/systemd/system/sc.service.wants/sc@8001.service

 
  # - name: Copia Config Baixado
  #   copy: 
  #     src: ./config/sc_worker.config
  #     dest: /etc/init/
  #     owner: saucelabs
  #     group: saucelabs        

  - name: execute instalacao do saucelabs
    shell: "{{saucelabs_dir}}/bin/sc -u danilo.ischiavolini -k ef3395f5-e975-4e1e-ac05-7abb0585ebb1 --doctor >> {{saucelabs_dir}}/bin/saucelabs-start.log &" 
    environment: "{{env}}"
    





